var projects = [
    {
        projectId: 'PR00001',
        projectName: 'THE TECH DEN',
        projectLogo: '../Asset/techden-logo.png',
        projectImage: '../banner/techden-banner.png, ../banner/techden-banner2.png, ../banner/techden-banner3.png',
        projectType: 'Computer Hardware and Software E-Commerce',
        projectCategory: 'Website, Featured',
        projectDate: '4 June 2023',
        projectDescription: 'The Tech Den is an e-commerce website designed to simplify the process of finding and purchasing computer hardware and software products.',
        projectTool: 'HTML, CSS, JavaScript, Bootstrap, JQuery',
        projectLink: 'https://github.com/BreezyCat/THE-TECH-DEN',
        downloadLink: 'https://github.com/BreezyCat/THE-TECH-DEN/archive/refs/heads/main.zip',
        projectIntroduction: 'Welcome to "The Tech Den," your one-stop destination for all things tech! We are delighted to introduce you to a world of cutting-edge technology and computing essentials. At The Tech Den, we understand the evolving needs of tech enthusiasts, gamers, professionals, and everyday users who rely on their computers for work and play.',
        projectBackground: 'In the fast-paced digital age, technology plays a pivotal role in our lives, transforming the way we work, connect, and entertain ourselves. Understanding the significance of staying up-to-date with the latest advancements, "The Tech Den" was born as a passion project of a group of tech-savvy individuals who saw a need for a comprehensive platform dedicated to high-quality computer components and accessories.<br><br>Our journey began with a vision to create an e-commerce platform that caters to the diverse requirements of computer enthusiasts. Whether you\'re a gamer seeking to boost your rig\'s performance, a professional in need of reliable hardware, or a student looking for budget-friendly upgrades, The Tech Den is designed to meet your specific needs.<br><br>Our product range includes a wide array of essential components, such as SSDs for lightning-fast storage, RAM for seamless multitasking, motherboards for robust system foundations, memory solutions to boost your computer\'s capacity, and much more. We meticulously curate our inventory to ensure that every product we offer meets the highest standards of quality and performance.<br><br>But our mission goes beyond just providing great products. We are dedicated to offering an exceptional shopping experience. Our user-friendly website, secure payment options, and efficient customer support ensure that your journey with us is seamless and satisfying.',
        projectSummary: 'The Tech Den is your ultimate tech destination, offering a curated selection of top-quality computer components and accessories. We\'re passionate about technology and committed to providing a seamless shopping experience for tech enthusiasts, gamers, professionals, and everyday users alike. Whether you\'re in need of SSDs, RAM, motherboards, or other tech essentials, we\'ve got you covered. Our mission is to make cutting-edge tech accessible to everyone and to keep you updated with the latest innovations in the world of technology. Join us at The Tech Den and explore the limitless possibilities of tech.',
        projectWebsite: 'https://breezycat.github.io/THE-TECH-DEN/html/home.html',
        projectPrototype: '',
        projectProtoLink: ''
    },
    {
        projectId: 'PR00002',
        projectName: 'LVinnamon',
        projectLogo: '../Asset/lvinnamon-logo.png',
        projectImage: '../banner/lvinnamon-banner.png, ../banner/lvinnamon-banner2.png, ../banner/lvinnamon-banner3.png',
        projectType: 'LVinnamon Company Profile Website Development',
        projectCategory: 'Website',
        projectDate: '20 May 2023',
        projectDescription: 'The LVinnamon website invites visitors to explore our cinnamon-infused world, offering a flavorful journey through our passion for baking and exceptional cinnamon-based treats.',
        projectTool: 'HTML, CSS, Javascript, JQuery',
        projectLink: 'https://github.com/RelaxCat/LVinnamon',
        downloadLink: 'https://github.com/RelaxCat/LVinnamon/archive/refs/heads/main.zip',
        projectIntroduction: 'Welcome to LVinnamon, where the aroma of freshly baked cinnamon rolls and the warmth of a good cup of tea or coffee come together to create a delightful experience. We are a globally renowned business specializing in the art of crafting and serving the most delectable cinnamon-infused treats, along with a selection of quality beverages. Our journey has been filled with the sweet scent of cinnamon and the joy of sharing our passion for baked goods with the world.',
        projectBackground: 'At LVinnamon, our story begins with a love for cinnamon, a spice that has been cherished for its warm and comforting flavor for centuries. We took this timeless ingredient and turned it into something truly magical–mouthwatering cinnamon rolls, cakes, and cookies that leave a lasting impression. With branches scattered across the globe, we have had the privilege of serving our delicious creations to cinnamon enthusiasts from all walks of life.<br><br> Our commitment to quality and taste is unwavering. Each cinnamon roll, cake, and cookie that leaves our ovens is a testament to our dedication to culinary excellence. We carefully select the finest ingredients, ensuring that every bite is a perfect balance of flavors and textures.<br><br>But there\'s more to discover on our website. We\'re thrilled to announce our exclusive "Happy Hour" tradition, held every Wednesday and Friday from 2 PM to 5 PM. During these magical hours, you can enjoy special deals and discounts on your favorite treats and beverages, making your visit to LVinnamon even sweeter. <br><br>Whether you\'re a cinnamon enthusiast, a lover of baked goods, or simply in search of a cozy spot to enjoy a cup of tea or coffee, LVinnamon welcomes you with open arms. Our commitment to providing a warm and inviting atmosphere, paired with irresistible flavors, remains at the heart of everything we do.',
        projectSummary: 'LVinnamon is a global destination for cinnamon-inspired treats. From our famous cinnamon rolls to cakes, cookies, and aromatic beverages, we bring the warmth of cinnamon to your palate. Our online presence now introduces our exclusive "Happy Hour" every Wednesday and Friday, 2 PM to 5 PM, offering special deals. Join us in savoring the essence of LVinnamon, where cinnamon becomes a delightful journey of taste and community.',
        projectWebsite: 'https://relaxcat.github.io/LVinnamon/index.html',
        projectPrototype: '',
        projectProtoLink: ''
    },
    {
        projectId: 'PR00003',
        projectName: 'Pestor',
        projectLogo: '../Asset/pestor-logo.png',
        projectImage: '../banner/pestor-banner.png, ../banner/pestor-banner2.png, ../banner/pestor-banner3.png',
        projectType: 'UI/UX Design for the Pestor App',
        projectCategory: 'UI/UX Design, Featured',
        projectDate: '18 May 2023',
        projectDescription: 'Pestor is an essential mobile app designed to simplify pest control, offering professional services and products for effective pest management in homes and buildings.',
        projectTool: 'Figma',
        projectLink: '',
        downloadLink: '',
        projectIntroduction: 'Pests are insects or animals that often cause damage to the buildings we inhabit. Common examples of pests found in our surroundings include termites, rats, cockroaches, fungi, and various other insects. The presence of pests not only results in structural damage to buildings but also poses a significant health threat to their inhabitants. The prevalence of pest infestations experienced by communities in their living spaces has turned this issue into a widespread concern, necessitating specialized solutions to address it.<br>Unfortunately, pest control services are still relatively scarce in Indonesia. This scarcity has left Indonesian residents struggling to find reliable pest control services for their homes or properties. Moreover, a considerable portion of the population lacks the knowledge required to tackle pest infestations themselves. To combat these issues, Pestor, has developed a mobile application available on both iOS and Android platforms. The Pestor application aims to assist users who encounter difficulties in eradicating and preventing pests in their homes or properties by offering professional pest control services. Additionally, the Pestor application provides users with pest control products that enable them to address and prevent pest issues independently at home.',
        projectBackground: 'Pest infestations have become a prevalent concern in many communities due to the potential harm they pose to both structures and human health. In Indonesia, the scarcity of pest control services has exacerbated this problem, leaving residents with limited options for addressing pest issues effectively. Furthermore, many individuals lack the knowledge and expertise required to combat these pests on their own. Consequently, there is a pressing need for accessible and professional pest control solutions to safeguard homes and buildings.<br>In response to this need, Pestor has taken the initiative to develop a comprehensive mobile application available on both iOS and Android platforms. This application aims to bridge the gap in pest control services by connecting users with skilled pest control professionals. Additionally, Pestor empowers users to take control of pest-related challenges by offering a range of pest control products that can be used independently in homes and properties. By combining expert services and user-friendly products, Pestor seeks to provide a holistic solution to the pest infestation problem in Indonesia.',
        projectSummary: 'Pest infestations pose a significant threat to both the structural integrity of buildings and the well-being of their occupants. In Indonesia, the scarcity of pest control services has created challenges for residents in addressing these issues effectively. Many lack the knowledge and resources to combat pests independently. To address these concerns, Pestor has developed a mobile application available on iOS and Android platforms. The Pestor application aims to provide professional pest control services, connecting users with experienced professionals who can eliminate and prevent pest infestations. Furthermore, Pestor offers a range of pest control products to empower users in taking proactive measures against pests in their homes and properties. By offering a comprehensive solution, Pestor seeks to alleviate the pest infestation problem in Indonesia and ensure the well-being of its residents.',
        projectWebsite: '',
        projectPrototype: 'https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FW3Vwxx6YDljU9UzSap4xDn%2FPestor%3Fpage-id%3D0%253A1%26node-id%3D3-399%26scaling%3Dscale-down%26starting-point-node-id%3D3%253A399%26mode%3Ddesign%26t%3DJWr7n04MBhgaVTur-1',
        projectProtoLink: 'https://www.figma.com/proto/W3Vwxx6YDljU9UzSap4xDn/Pestor?page-id=0%3A1&node-id=3-399&scaling=scale-down&starting-point-node-id=3%3A399&mode=design&t=JWr7n04MBhgaVTur-1'
    },
    {
        projectId: 'PR00004',
        projectName: 'BWorkshop',
        projectLogo: '',
        projectImage: '../banner/bworkshop-banner.png, ../banner/bworkshop-banner2.png, ../banner/bworkshop-banner3.png',
        projectType: 'App Development for Vehicle Spare Parts and Inventory Management',
        projectCategory: 'Java Application',
        projectDate: '13 Dec 2022',
        projectDescription: 'BWorkshop streamlines vehicle spare part procurement and inventory management. With user-friendly features and a JavaFX-based interface, it offers a seamless experience for users and administrators.',
        projectTool: 'Java',
        projectLink: 'https://github.com/RelaxCat/BWorkshop',
        downloadLink: 'https://github.com/RelaxCat/BWorkshop/archive/refs/heads/main.zip',
        projectIntroduction: 'Step into the world of BWorkshop, your go-to application for convenient vehicle spare part purchases. Designed with user-friendliness in mind, BWorkshop simplifies the process of acquiring essential spare parts for your vehicles.<br><br>Administrators are also well-equipped with the power to effortlessly manage the inventory. They can update, add, or remove items with ease, ensuring that the catalog is always up-to-date and aligned with your needs.<br><br>Built with JavaFX and integrated with a MySQL database through the XAMPP connector, BWorkshop promises a seamless and efficient spare part procurement experience for users and administrators alike. Discover a smarter way to manage your vehicle spare part needs with BWorkshop.',
        projectBackground: '',
        projectSummary: '',
        projectWebsite: '',
        projectPrototype: '',
        projectProtoLink: ''
    },
    {
        projectId: 'PR00005',
        projectName: 'Weather Now',
        projectLogo: '../Asset/weathernow-logo.png',
        projectImage: '../banner/weathernow-banner.png, ../banner/weathernow-banner2.png, ../banner/weathernow-banner3.png',
        projectType: 'Weather App Development for Real-Time Weather Updates and Forecasts',
        projectCategory: 'Website, Featured, UI/UX Design',
        projectDate: '17 Oct 2023',
        projectDescription: 'The Weather App provides up-to-the-minute weather updates and current conditions to keep you informed about what\'s happening in your area',
        projectTool: 'HTML, CSS, Javascript, React',
        projectLink: 'https://github.com/BreezyCat/React-WeatherApp',
        downloadLink: 'https://github.com/BreezyCat/React-WeatherNow/archive/refs/heads/main.zip',
        projectIntroduction: 'Welcome to our Weather App, a project that symbolizes our collective dedication to mastering React, a versatile JavaScript library for crafting dynamic user interfaces. This application is not only a testament to our passion for programming but also a practical tool designed with users like you in mind.<br><br>At the core of our Weather App is the pursuit of providing a seamless and user-friendly experience for checking weather forecasts. React, with its robust capabilities, has allowed us to create a dynamic application that responds to your interactions. The utilization of the OpenWeatherMap API guarantees that the weather information you receive is both accurate and current. It empowers you to plan your day effectively and stay informed about changing weather conditions.<br><br>To enhance the app\'s user experience, we\'ve incorporated a selection of weather icons sourced from Dovora\'s Weather Icons. These icons not only add an aesthetic charm to the app but also provide a quick visual reference to grasp weather conditions intuitively. Our commitment to user-centric design goes hand in hand with our mission to make the Weather App both informative and visually appealing.',
        projectBackground: '',
        projectSummary: '',
        projectWebsite: 'https://breezycat.github.io/React-WeatherNow/ ',
        projectPrototype: '',
        projectProtoLink: ''
    },
    {
        projectId: 'PR00006',
        projectName: 'Achord.ly',
        projectLogo: '',
        projectImage: '../banner/achordly-banner.png, ../banner/achordly-banner2.png, ../banner/achordly-banner3.png',
        projectType: 'UI/UX Design for Achord.ly Music Application',
        projectCategory: 'UI/UX Design',
        projectDate: '15 Oct 2023',
        projectDescription: 'Achord.ly simplifies the process of exploring a wide range of musical chords and video tutorials, enhancing your musical journey with ease and convenience.',
        projectTool: 'Figma',
        projectLink: '',
        downloadLink: '',
        projectIntroduction: 'Introducing Achord.ly, a musical community rooted in Bandung since 2017. Born from a passion for music, Achord.ly offers a unique space for musicians and enthusiasts to hone their skills, exchange ideas, and share their love for playing instruments. Over the years, this community has thrived, attracting an ever-growing number of music aficionados, united by a common goal of musical improvement and connection.',
        projectBackground: 'In light of the ongoing COVID-19 pandemic, the year-end meeting of Achord.ly members sparked an innovative idea. Recognizing that aspiring musicians from far beyond Bandung\'s borders desired to be part of the Achord.ly community to refine their musical talents, it became evident that a digital platform was needed. However, the pandemic restricted the community from accepting members from distant locations. This predicament led to the proposal of creating a digital platform that would transcend geographical boundaries and enable music enthusiasts from all corners of Indonesia to sharpen their musical abilities.<br><br>As the initial step, the focus will be on developing a mobile application for Android and iOS operating systems, aptly named Achord.ly. This application, in essence, will serve as a reservoir for chords, offering users a vast library of chord progressions for their favorite songs, complemented by instructional video tutorials on how to play them.',
        projectSummary: 'As the initial step, the focus will be on developing a mobile application for Android and iOS operating systems, aptly named Achord.ly. This application, in essence, will serve as a reservoir for chords, offering users a vast library of chord progressions for their favorite songs, complemented by instructional video tutorials on how to play them.',
        projectWebsite: '',
        projectPrototype: 'https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FD8EMvwBjYH9hW726z1Ikls%2FAchord.ly%3Fnode-id%3D1-164%26starting-point-node-id%3D1%253A2%26scaling%3Dscale-down%26mode%3Ddesign%26t%3DPaz9VP5qZ23CdkuG-1',
        projectProtoLink: 'https://www.figma.com/proto/D8EMvwBjYH9hW726z1Ikls/Achord.ly?node-id=1-164&starting-point-node-id=1%3A2&mode=design&t=Paz9VP5qZ23CdkuG-1'
    },
    {
        projectId: '',
        projectName: '',
        projectLogo: '',
        projectImage: '../banner/lvinnamon-banner.png',
        projectType: '',
        projectCategory: '',
        projectDate: '',
        projectDescription: '',
        projectTool: '',
        projectLink: '',
        downloadLink: '',
        projectIntroduction: '',
        projectBackground: '',
        projectSummary: '',
        projectWebsite: '',
        projectPrototype: '',
        projectProtoLink: ''
    },
]